using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AudioControlLib.AudioMixer.Enums
{
    enum Mixer_ObjectFlag : uint
    {
        HANDLE = 0x80000000,
        MIXER = 0x00000000,
        HMIXER = (HANDLE | MIXER),
        WAVEOUT = 0x10000000,
        HWAVEOUT = (HANDLE | WAVEOUT),
        WAVEIN = 0x20000000,
        HWAVEIN = (HANDLE | WAVEIN),
        MIDIOUT = 0x30000000,
        HMIDIOUT = (HANDLE | MIDIOUT),
        MIDIIN = 0x40000000,
        HMIDIIN = (HANDLE | MIDIIN),
        AUX = 0x50000000,

        MIXER_GETCONTROLDETAILSF_VALUE = 0,
        MIXER_SETCONTROLDETAILSF_VALUE = 0,
        MIXER_GETCONTROLDETAILSF_LISTTEXT = 1,
        MIXER_SETCONTROLDETAILSF_LISTTEXT = 1,
        MIXER_GETCONTROLDETAILSF_QUERYMASK = 0xF,
        MIXER_SETCONTROLDETAILSF_QUERYMASK = 0xF,
        MIXER_GETLINECONTROLSF_QUERYMASK = 0xF,

        MIXER_GETLINECONTROLSF_ALL = 0,
        MIXER_GETLINECONTROLSF_ONEBYID = 1,
        MIXER_GETLINECONTROLSF_ONEBYTYPE = 2,

        MIXER_GETLINEINFOF_DESTINATION = 0,
        MIXER_GETLINEINFOF_SOURCE = 1,
        MIXER_GETLINEINFOF_LINEID = 2,
        MIXER_GETLINEINFOF_COMPONENTTYPE = 3,
        MIXER_GETLINEINFOF_TARGETTYPE = 4,
        MIXER_GETLINEINFOF_QUERYMASK = 0xF,
    }
}
